# Generated by Django 4.1.7 on 2024-03-02 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0003_lesson_product_product_max_group_product_min_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="system.product"
            ),
        ),
    ]
